version: '3'
services:
  back:
    build:
      dockerfile: ./Dockerfile
      args:
        - DB_PASSWORD=1234
        - DB_USER=root
        - PROFILE=local
        - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/certvet?useUnicode=true&characterEncoding=utf8&useSSL=true&allowPublicKeyRetrieval=true
        - ARGS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5000 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
        - MAIL_PASS=yvayjysaldpubihr
        - MAIL_USR=cartvet.ifsp@gmail.com
    ports:
      - '8443:8443'
      - '5000:5000'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/certvet?useUnicode=true&characterEncoding=utf8&useSSL=true&allowPublicKeyRetrieval=true
      - ARGS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5000 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=local
      - DB_PASSWORD=1234
      - DB_USER=root
      - MAIL_PASS=yvayjysaldpubihr
      - MAIL_USR=cartvet.ifsp@gmail.com