logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG
          core.JdbcTemplate: DEBUG
spring:
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.h2.Driver
    #    hikari:
    #      connection-test-query: SELECT NOW();
    #      connection-timeout: 20000 # 20s
    #      idle-timeout: 10000 # 10s
    #      maximum-pool-size: 5
    #      minimum-idle: 2
    #      pool-name: certvetPool
    init:
      platform: h2
    name: certvetDB
    #    type: com.zaxxer.hikari.HikariDataSource
    type: org.h2.jdbcx.JdbcDataSource
    url: "jdbc:h2:mem:test"
  #    url: ${SPRING_DATASOURCE_URL}
  #    username: ${DB_USER}
  #    password: ${DB_PASSWORD}
  jpa:
    database: h2
    generate-ddl: true
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        globally_quoted_identifiers: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      platform: h2
      continue-on-error: true
      mode: always
  # Gmail SMTP
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: ${MAIL_USR}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 80
app:
  jwt:
    secret: test
    expiration: "864000000"
  default:
    pdf:
      password: ${DEFAULT_PDF_PASS}