logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG
          core.JdbcTemplate: DEBUG
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT NOW();
      connection-timeout: 20000 # 20s
      idle-timeout: 10000 # 10s
      maximum-pool-size: 5
      minimum-idle: 2
      pool-name: certvetPool
    init:
      platform: mysql
    name: certvetDB
    type: com.zaxxer.hikari.HikariDataSource
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      platform: mysql
      continue-on-error: true
      mode: always
# Gmail SMTP
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: ${MAIL_USR}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    templates: "path"
server:
  port:
    8443
#  ssl:
#    certificate: "classpath:keystore/public.crt"
#    certificate-private-key: "classpath:keystore/privatekey.pem"
  http2:
    enabled: true
app:
  jwt:
    secret: qwertyuiosdfghjk
    expiration: "864000000"
api:
  version: "v0.0.2"
  description: "Interface de aplicação para sistema CertVet"
  server:
    # TODO: Checar a URL que será a base no momento do deploy
    url: "https://certvet-back.us-east-1.elasticbeanstalk.com:8443"
springdoc:
  swagger-ui:
    path: "/api/swagger-ui.html"
