# # CREATE SCHEMA IF NOT EXISTS CERTVET;
# # USE CERTVET;
# -- MySQL Script generated by MySQL Workbench
# -- Wed Dec  7 21:01:12 2022
# -- Model: New Model    Version: 1.0
# -- MySQL Workbench Forward Engineering
#
# SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
# SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
# SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
#
# -- -----------------------------------------------------
# -- Schema mydb
# -- -----------------------------------------------------
# -- -----------------------------------------------------
# -- Schema CERTVET
# -- -----------------------------------------------------
# DROP SCHEMA IF EXISTS `CERTVET` ;
#
# -- -----------------------------------------------------
# -- Schema Rocket
# -- -----------------------------------------------------
# CREATE SCHEMA IF NOT EXISTS `CERTVET` DEFAULT CHARACTER SET latin1 ;
# USE `CERTVET` ;
#
# -- -----------------------------------------------------
# -- Table `CERTVET`.`Usuario`
# -- -----------------------------------------------------
# DROP TABLE IF EXISTS `CERTVET`.`Usuario` ;
#
# CREATE TABLE IF NOT EXISTS `CERTVET`.`Usuario` (
#                                                  `idUsuario` INT(11) NOT NULL,
#                                                  `Nome` VARCHAR(45) NULL DEFAULT NULL,
#                                                  `senha` VARCHAR(45) NULL DEFAULT NULL,
#                                                  `email` VARCHAR(45) NULL DEFAULT NULL,
#                                                  `crmv` VARCHAR(45) NULL DEFAULT NULL,
#                                                  PRIMARY KEY (`idUsuario`))
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = latin1;
#
#
# -- -----------------------------------------------------
# -- Table `CERTVET`.`animal`
# -- -----------------------------------------------------
# DROP TABLE IF EXISTS `CERTVET`.`animal` ;
#
# CREATE TABLE IF NOT EXISTS `CERTVET`.`animal` (
#                                                 `idanimal` INT(11) NOT NULL,
#                                                 `Nome` VARCHAR(45) NULL DEFAULT NULL,
#                                                 `especie` VARCHAR(45) NULL DEFAULT NULL,
#                                                 `sexo` VARCHAR(45) NULL DEFAULT NULL,
#                                                 PRIMARY KEY (`idanimal`))
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = latin1;
#
#
# -- -----------------------------------------------------
# -- Table `CERTVET`.`clinica`
# -- -----------------------------------------------------
# DROP TABLE IF EXISTS `CERTVET`.`clinica` ;
#
# CREATE TABLE IF NOT EXISTS `CERTVET`.`clinica` (
#                                                  `cnpj` INT(11) NOT NULL,
#                                                  `razao_social` INT(11) NULL DEFAULT NULL,
#                                                  PRIMARY KEY (`cnpj`))
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = latin1;
#
#
# -- -----------------------------------------------------
# -- Table `CERTVET`.`usuario_x_clinica`
# -- -----------------------------------------------------
# DROP TABLE IF EXISTS `CERTVET`.`usuario_x_clinica` ;
#
# CREATE TABLE IF NOT EXISTS `CERTVET`.`usuario_x_clinica` (
#                                                            `idusuario_x_clinica` INT(11) NOT NULL,
#                                                            `idUsuario` INT(11) NOT NULL,
#                                                            `idClinica` INT(11) NOT NULL,
#                                                            PRIMARY KEY (`idusuario_x_clinica`),
#                                                            CONSTRAINT `fk_idclinica_u`
#                                                                FOREIGN KEY (`idClinica`)
#                                                                    REFERENCES `CERTVET`.`clinica` (`cnpj`)
#                                                                    ON DELETE NO ACTION
#                                                                    ON UPDATE NO ACTION,
#                                                            CONSTRAINT `fk_usuario_u`
#                                                                FOREIGN KEY (`idUsuario`)
#                                                                    REFERENCES `CERTVET`.`Usuario` (`idUsuario`)
#                                                                    ON DELETE NO ACTION
#                                                                    ON UPDATE NO ACTION)
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = latin1;
#
# CREATE INDEX `fk_usuario_u_idx` ON `CERTVET`.`usuario_x_clinica` (`idUsuario` ASC)  ;
#
# CREATE INDEX `fk_idclinica_u_idx` ON `CERTVET`.`usuario_x_clinica` (`idClinica` ASC)  ;
#
#
# -- -----------------------------------------------------
# -- Table `CERTVET`.`agendamento`
# -- -----------------------------------------------------
# DROP TABLE IF EXISTS `CERTVET`.`agendamento` ;
#
# CREATE TABLE IF NOT EXISTS `CERTVET`.`agendamento` (
#                                                      `idagendamento` INT(11) NOT NULL PRIMARY KEY,
#                                                      `data` DATETIME NULL DEFAULT NULL,
#                                                      `animal` INT(11) NOT NULL,
#                                                      `usuario_x_clinica` INT(11) NULL DEFAULT NULL,
#                                                      CONSTRAINT `fk_animal1`
#                                                          FOREIGN KEY (`animal`)
#                                                              REFERENCES `CERTVET`.`animal` (`idanimal`)
#                                                              ON DELETE NO ACTION
#                                                              ON UPDATE NO ACTION,
#                                                      CONSTRAINT `fk_clinica1`
#                                                          FOREIGN KEY (`usuario_x_clinica`)
#                                                              REFERENCES `CERTVET`.`usuario_x_clinica` (`idusuario_x_clinica`)
#                                                              ON DELETE NO ACTION
#                                                              ON UPDATE NO ACTION)
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = latin1;
#
# CREATE INDEX `fk_clinica1_idx` ON `CERTVET`.`agendamento` (`usuario_x_clinica` ASC) ;
#
#
# -- -----------------------------------------------------
# -- Table `CERTVET`.`parentesco`
# -- -----------------------------------------------------
# DROP TABLE IF EXISTS `CERTVET`.`parentesco` ;
#
# CREATE TABLE IF NOT EXISTS `CERTVET`.`parentesco` (
#                                                     `parentesco` INT(11) NOT NULL,
#                                                     `grau_parentesco` VARCHAR(45) NULL DEFAULT NULL,
#                                                     PRIMARY KEY (`parentesco`))
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = latin1;
#
#
# -- -----------------------------------------------------
# -- Table `CERTVET`.`animal_x_parentesco`
# -- -----------------------------------------------------
# DROP TABLE IF EXISTS `CERTVET`.`animal_x_parentesco` ;
#
# CREATE TABLE IF NOT EXISTS `CERTVET`.`animal_x_parentesco` (
#                                                              `idanimal` INT(11) NOT NULL,
#                                                              `id_parentesco` INT(11) NOT NULL,
#                                                              `id_parente` INT(11) NOT NULL,
#                                                              PRIMARY KEY (`idanimal`, `id_parentesco`, `id_parente`),
#                                                              CONSTRAINT `fk_animal`
#                                                                  FOREIGN KEY (`idanimal`)
#                                                                      REFERENCES `CERTVET`.`animal` (`idanimal`)
#                                                                      ON DELETE NO ACTION
#                                                                      ON UPDATE NO ACTION,
#                                                              CONSTRAINT `fk_idparente`
#                                                                  FOREIGN KEY (`id_parente`)
#                                                                      REFERENCES `CERTVET`.`animal` (`idanimal`)
#                                                                      ON DELETE NO ACTION
#                                                                      ON UPDATE NO ACTION,
#                                                              CONSTRAINT `fk_parentesco`
#                                                                  FOREIGN KEY (`id_parentesco`)
#                                                                      REFERENCES `CERTVET`.`parentesco` (`parentesco`)
#                                                                      ON DELETE NO ACTION
#                                                                      ON UPDATE NO ACTION)
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = latin1;
#
# CREATE INDEX `fk_parentesco_idx` ON `CERTVET`.`animal_x_parentesco` (`id_parentesco` ASC)  ;
#
# CREATE INDEX `fk_idparente_idx` ON `CERTVET`.`animal_x_parentesco` (`id_parente` ASC)  ;
#
#
# -- -----------------------------------------------------
# -- Table `CERTVET`.`animal_x_tutor`
# -- -----------------------------------------------------
# DROP TABLE IF EXISTS `CERTVET`.`animal_x_tutor` ;
#
# CREATE TABLE IF NOT EXISTS `CERTVET`.`animal_x_tutor` (
#                                                         `idusuario` INT(11) NOT NULL,
#                                                         `idanimal` INT(11) NULL DEFAULT NULL,
#                                                         CONSTRAINT `idanimal`
#                                                             FOREIGN KEY (`idanimal`)
#                                                                 REFERENCES `CERTVET`.`animal` (`idanimal`)
#                                                                 ON DELETE NO ACTION
#                                                                 ON UPDATE NO ACTION,
#                                                         CONSTRAINT `idusurio`
#                                                             FOREIGN KEY (`idusuario`)
#                                                                 REFERENCES `CERTVET`.`usuario_x_clinica` (`idusuario_x_clinica`)
#                                                                 ON DELETE NO ACTION
#                                                                 ON UPDATE NO ACTION)
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = latin1;
#
# CREATE INDEX `idanimal_idx` ON `CERTVET`.`animal_x_tutor` (`idanimal` ASC)  ;
#
# CREATE INDEX `idusurio_idx` ON `CERTVET`.`animal_x_tutor` (`idusuario` ASC)  ;
#
#
# -- -----------------------------------------------------
# -- Table `CERTVET`.`cirurgia`
# -- -----------------------------------------------------
# DROP TABLE IF EXISTS `CERTVET`.`cirurgia` ;
#
# CREATE TABLE IF NOT EXISTS `CERTVET`.`cirurgia` (
#                                                   `idcirurgia` INT(11) NOT NULL,
#                                                   `descricao_cirurgia` VARCHAR(45) NULL DEFAULT NULL,
#                                                   PRIMARY KEY (`idcirurgia`))
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = latin1;
#
#
# -- -----------------------------------------------------
# -- Table `CERTVET`.`medicamentos`
# -- -----------------------------------------------------
# DROP TABLE IF EXISTS `CERTVET`.`medicamentos` ;
#
# CREATE TABLE IF NOT EXISTS `CERTVET`.`medicamentos` (
#                                                       `idmedicamentos` INT(11) NOT NULL,
#                                                       `nome` VARCHAR(45) NULL DEFAULT NULL,
#                                                       `codbarra` INT(11) NULL DEFAULT NULL,
#                                                       PRIMARY KEY (`idmedicamentos`))
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = latin1;
#
#
# -- -----------------------------------------------------
# -- Table `CERTVET`.`medicamento_x_estoque`
# -- -----------------------------------------------------
# DROP TABLE IF EXISTS `CERTVET`.`medicamento_x_estoque` ;
#
# CREATE TABLE IF NOT EXISTS `CERTVET`.`medicamento_x_estoque` (
#                                                                `idmedicamento` INT(11) NOT NULL,
#                                                                `quantidade_med` INT(11) NULL DEFAULT NULL,
#                                                                `clinica` INT(11) NULL DEFAULT NULL,
#                                                                `quantidade` VARCHAR(45) NULL DEFAULT NULL,
#                                                                PRIMARY KEY (`idmedicamento`),
#                                                                CONSTRAINT `fk_clinica_m_e`
#                                                                    FOREIGN KEY (`clinica`)
#                                                                        REFERENCES `CERTVET`.`clinica` (`cnpj`)
#                                                                        ON DELETE NO ACTION
#                                                                        ON UPDATE NO ACTION,
#                                                                CONSTRAINT `fk_m`
#                                                                    FOREIGN KEY (`idmedicamento`)
#                                                                        REFERENCES `CERTVET`.`medicamentos` (`idmedicamentos`)
#                                                                        ON DELETE NO ACTION
#                                                                        ON UPDATE NO ACTION)
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = latin1;
#
# CREATE INDEX `fk_clinica_m_e_idx` ON `CERTVET`.`medicamento_x_estoque` (`clinica` ASC)  ;
#
#
# -- -----------------------------------------------------
# -- Table `CERTVET`.`prontuario`
# -- -----------------------------------------------------
# DROP TABLE IF EXISTS `CERTVET`.`prontuario` ;
#
# CREATE TABLE IF NOT EXISTS `CERTVET`.`prontuario` (
#                                                     `idprontuario` INT(11) NOT NULL,
#                                                     `data` DATETIME NULL DEFAULT NULL,
#                                                     `idanimal` INT(11) NULL DEFAULT NULL,
#                                                     `usuario_x_clinica` INT(11) NULL DEFAULT NULL,
#                                                     PRIMARY KEY (`idprontuario`),
#                                                     CONSTRAINT `fk_idanimal_prontuario`
#                                                         FOREIGN KEY (`idanimal`)
#                                                             REFERENCES `CERTVET`.`animal` (`idanimal`)
#                                                             ON DELETE NO ACTION
#                                                             ON UPDATE NO ACTION,
#                                                     CONSTRAINT `fk_usuario_clinica_p`
#                                                         FOREIGN KEY (`usuario_x_clinica`)
#                                                             REFERENCES `CERTVET`.`usuario_x_clinica` (`idusuario_x_clinica`)
#                                                             ON DELETE NO ACTION
#                                                             ON UPDATE NO ACTION)
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = latin1;
#
# CREATE INDEX `fk_idanimal_prontuario_idx` ON `CERTVET`.`prontuario` (`idanimal` ASC)  ;
#
# CREATE INDEX `fk_usuario_clinica_p_idx` ON `CERTVET`.`prontuario` (`usuario_x_clinica` ASC)  ;
#
#
# -- -----------------------------------------------------
# -- Table `CERTVET`.`cirurgia_x_prontuario`
# -- -----------------------------------------------------
# DROP TABLE IF EXISTS `CERTVET`.`cirurgia_x_prontuario` ;
#
# CREATE TABLE IF NOT EXISTS `CERTVET`.`cirurgia_x_prontuario` (
#                                                                `idcirurgia` INT(11) NOT NULL,
#                                                                `idprontuario` INT(11) NOT NULL,
#                                                                `medicamentos` INT(11) NULL DEFAULT NULL,
#                                                                PRIMARY KEY (`idcirurgia`, `idprontuario`),
#                                                                CONSTRAINT `fk_idcirugia_c`
#                                                                    FOREIGN KEY (`idcirurgia`)
#                                                                        REFERENCES `CERTVET`.`cirurgia` (`idcirurgia`)
#                                                                        ON DELETE NO ACTION
#                                                                        ON UPDATE NO ACTION,
#                                                                CONSTRAINT `fk_medicamentos_CP`
#                                                                    FOREIGN KEY (`medicamentos`)
#                                                                        REFERENCES `CERTVET`.`medicamento_x_estoque` (`idmedicamento`)
#                                                                        ON DELETE NO ACTION
#                                                                        ON UPDATE NO ACTION,
#                                                                CONSTRAINT `fk_prontuario_c`
#                                                                    FOREIGN KEY (`idprontuario`)
#                                                                        REFERENCES `CERTVET`.`prontuario` (`idprontuario`)
#                                                                        ON DELETE NO ACTION
#                                                                        ON UPDATE NO ACTION)
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = latin1;
#
# CREATE INDEX `fk_prontuario_c_idx` ON `CERTVET`.`cirurgia_x_prontuario` (`idprontuario` ASC)  ;
#
# CREATE INDEX `fk_medicamentos_CP_idx` ON `CERTVET`.`cirurgia_x_prontuario` (`medicamentos` ASC)  ;
#
#
# -- -----------------------------------------------------
# -- Table `CERTVET`.`exames`
# -- -----------------------------------------------------
# DROP TABLE IF EXISTS `CERTVET`.`exames` ;
#
# CREATE TABLE IF NOT EXISTS `CERTVET`.`exames` (
#                                                 `idexames` INT(11) NOT NULL,
#                                                 `descricao` VARCHAR(45) NULL DEFAULT NULL,
#                                                 PRIMARY KEY (`idexames`))
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = latin1;
#
#
# -- -----------------------------------------------------
# -- Table `CERTVET`.`exame_x_prontuario`
# -- -----------------------------------------------------
# DROP TABLE IF EXISTS `CERTVET`.`exame_x_prontuario` ;
#
# CREATE TABLE IF NOT EXISTS `CERTVET`.`exame_x_prontuario` (
#                                                             `idprontuario_a` INT(11) NOT NULL,
#                                                             `idexame` INT(11) NOT NULL,
#                                                             `medicamentos` INT(11) NULL DEFAULT NULL,
#                                                             PRIMARY KEY (`idprontuario_a`, `idexame`),
#                                                             CONSTRAINT `fk_Med`
#                                                                 FOREIGN KEY (`medicamentos`)
#                                                                     REFERENCES `CERTVET`.`medicamento_x_estoque` (`idmedicamento`)
#                                                                     ON DELETE NO ACTION
#                                                                     ON UPDATE NO ACTION,
#                                                             CONSTRAINT `fk_a`
#                                                                 FOREIGN KEY (`idprontuario_a`)
#                                                                     REFERENCES `CERTVET`.`prontuario` (`idprontuario`)
#                                                                     ON DELETE NO ACTION
#                                                                     ON UPDATE NO ACTION,
#                                                             CONSTRAINT `fk_b`
#                                                                 FOREIGN KEY (`idexame`)
#                                                                     REFERENCES `CERTVET`.`exames` (`idexames`)
#                                                                     ON DELETE NO ACTION
#                                                                     ON UPDATE NO ACTION)
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = latin1;
#
# CREATE INDEX `fk_b_idx` ON `CERTVET`.`exame_x_prontuario` (`idexame` ASC)  ;
#
# CREATE INDEX `fk_Med_idx` ON `CERTVET`.`exame_x_prontuario` (`medicamentos` ASC)  ;
#
#
# -- -----------------------------------------------------
# -- Table `CERTVET`.`procedimentos`
# -- -----------------------------------------------------
# DROP TABLE IF EXISTS `CERTVET`.`procedimentos` ;
#
# CREATE TABLE IF NOT EXISTS `CERTVET`.`procedimentos` (
#                                                        `idprocedimentos` INT(11) NOT NULL,
#                                                        `descricao_procedimentos` VARCHAR(45) NULL DEFAULT NULL,
#                                                        PRIMARY KEY (`idprocedimentos`))
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = latin1;
#
#
# -- -----------------------------------------------------
# -- Table `CERTVET`.`procedimentos_x_prontuario`
# -- -----------------------------------------------------
# DROP TABLE IF EXISTS `CERTVET`.`procedimentos_x_prontuario` ;
#
# CREATE TABLE IF NOT EXISTS `CERTVET`.`procedimentos_x_prontuario` (
#                                                                     `idprocedimentos` INT(11) NOT NULL,
#                                                                     `idprontuario` INT(11) NOT NULL,
#                                                                     `medicamentos` INT(11) NULL DEFAULT NULL,
#                                                                     PRIMARY KEY (`idprocedimentos`, `idprontuario`),
#                                                                     CONSTRAINT `fk_idprocedimento_p`
#                                                                         FOREIGN KEY (`idprocedimentos`)
#                                                                             REFERENCES `CERTVET`.`procedimentos` (`idprocedimentos`)
#                                                                             ON DELETE NO ACTION
#                                                                             ON UPDATE NO ACTION,
#                                                                     CONSTRAINT `fk_idprontuario`
#                                                                         FOREIGN KEY (`idprontuario`)
#                                                                             REFERENCES `CERTVET`.`prontuario` (`idprontuario`)
#                                                                             ON DELETE NO ACTION
#                                                                             ON UPDATE NO ACTION,
#                                                                     CONSTRAINT `fk_medicamentos_p`
#                                                                         FOREIGN KEY (`medicamentos`)
#                                                                             REFERENCES `CERTVET`.`medicamento_x_estoque` (`idmedicamento`)
#                                                                             ON DELETE NO ACTION
#                                                                             ON UPDATE NO ACTION)
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = latin1;
#
# CREATE INDEX `fk_idprontuario_idx` ON `CERTVET`.`procedimentos_x_prontuario` (`idprontuario` ASC)  ;
#
# CREATE INDEX `fk_medicamentos_p_idx` ON `CERTVET`.`procedimentos_x_prontuario` (`medicamentos` ASC)  ;
#
#
# -- -----------------------------------------------------
# -- Table `CERTVET`.`roles`
# -- -----------------------------------------------------
# DROP TABLE IF EXISTS `CERTVET`.`roles` ;
#
# CREATE TABLE IF NOT EXISTS `CERTVET`.`roles` (
#                                                `idroles` INT(11) NOT NULL,
#                                                `nome` VARCHAR(45) NULL DEFAULT NULL,
#                                                PRIMARY KEY (`idroles`))
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = latin1;
#
#
# -- -----------------------------------------------------
# -- Table `CERTVET`.`usuario_x_roles`
# -- -----------------------------------------------------
# DROP TABLE IF EXISTS `CERTVET`.`usuario_x_roles` ;
#
# CREATE TABLE IF NOT EXISTS `CERTVET`.`usuario_x_roles` (
#                                                          `idusuario` INT(11) NOT NULL,
#                                                          `idrole` INT(11) NOT NULL,
#                                                          PRIMARY KEY (`idusuario`, `idrole`),
#                                                          CONSTRAINT `fk_role`
#                                                              FOREIGN KEY (`idrole`)
#                                                                  REFERENCES `CERTVET`.`roles` (`idroles`)
#                                                                  ON DELETE NO ACTION
#                                                                  ON UPDATE NO ACTION,
#                                                          CONSTRAINT `fk_ususario`
#                                                              FOREIGN KEY (`idusuario`)
#                                                                  REFERENCES `CERTVET`.`Usuario` (`idUsuario`)
#                                                                  ON DELETE NO ACTION
#                                                                  ON UPDATE NO ACTION)
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = latin1;
#
# CREATE INDEX `fk_role_idx` ON `CERTVET`.`usuario_x_roles` (`idrole` ASC)  ;
#
#
# SET SQL_MODE=@OLD_SQL_MODE;
# SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
# SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
